#!/bin/sh

start() {
    echo "First Boot, setting up partitions. Do not Power off."
    echo ',,c' | sfdisk --force -a -N 3 /dev/mmcblk0
    echo "Finished, rebooting"
    rm $0
    reboot
}

case "$1" in
    start)
        "$1";;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
