#!/bin/sh

start() {
    echo 1 > /sys/devices/platform/leds/leds/blackhat:green:usr/brightness

    source /mnt/blackhat.conf
    modprobe pwm_bl
    modprobe panel_sitronix_st7701
    echo "Welcome to BlackhatOS."
}

stop() {
    echo 0 > /sys/devices/platform/leds/leds/blackhat:green:usr/brightness

    source /mnt/blackhat.conf
    rmmod pwm_bl
    rmmod panel_sitronix_st7701
}

case "$1" in
    start|stop)
        "$1";;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
