#!/bin/sh
#
# Start the WiFi AP...
#

case "$1" in
  start)
    printf "Starting hostapd (wlan1): "
    hostapd /etc/hostapd.conf -B
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping hostapd: "
    kill $(pidof hostapd)
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
