src/gz base http://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a7_neon-vfpv4/base
src/gz packages http://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a7_neon-vfpv4/packages
src/gz luci http://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a7_neon-vfpv4/luci
src/gz routing http://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a7_neon-vfpv4/routing
dest root /
option overlay_root /overlay
